### ISSUE TITLE
`error C2676: binary '/': 'const lexyd:_lit<unsigned char,126>' does not define this operator` on MSVC

### ISSUE THREAD

**Issue by GraCoder** [OpenVicProject/OpenVic-Dataloader#31]
![cmd_dUD8vgfi6n](https://github.com/OpenVicProject/OpenVic-Dataloader/assets/16001348/6b7f9044-1fc3-4737-8436-99c60731226c)

**Comment by GraCoder** [comment]
[1.txt](https://github.com/OpenVicProject/OpenVic-Dataloader/files/13600578/1.txt)
![devenv_AdwHhSaNa6](https://github.com/OpenVicProject/OpenVic-Dataloader/assets/16001348/0e925174-2fb5-4822-9804-fb0ea8b3e46f)

**Comment by GraCoder** [comment]
![cmd_aLKLyziLH4](https://github.com/OpenVicProject/OpenVic-Dataloader/assets/16001348/2bc5ba3e-2344-477c-9784-49d114e73518)

**Comment by Spartan322** [comment]
I don't have a windows machine I can test this on, I can only recommend you use mingw or clang for now: `scons use_mingw=yes` or `scons use_llvm=yes`

**Comment by Spartan322** [comment]
It appears to be fault of a new update to the Visual C++ compiler, version 19.38 is now violating the C++ standard that it once followed.

**Comment by GraCoder** [comment]
make no sense to me , the same code i copyed to another test project works fine. 
![5DKTyABuQx](https://github.com/OpenVicProject/OpenVic-Dataloader/assets/16001348/f35af034-a291-434c-8c8d-541281d1978b)

i move the #include "SimpleGrammar.hpp" to the bottom it worked.
so i assume its the your code mess with lexy

![5DKTyABuQx](https://github.com/OpenVicProject/OpenVic-Dataloader/assets/16001348/b76e34ec-773b-49d1-90cd-486a3200bf4b)

**Comment by GraCoder** [comment]
wrong pic  this one 
![cmd_tFLGK7abOA](https://github.com/OpenVicProject/OpenVic-Dataloader/assets/16001348/ce1420c3-8211-4f96-8ac7-f74e670cd101)

**Comment by Spartan322** [comment]
This only started being reported as a problem in Visual C++ 19.38, every case for which it has occurred has only been on that version of the compiler, it does not appear in GCC or Clang and neither does it appear before Visual C++ 19.38, so this is a compiler regression violating the C++ standard that was previously acceptable. Also why is there a red error squiggle following the SimpleGrammar.hpp? As well it should be corrected to `#include "v2script/SimpleGrammar.hpp"` honestly. But there should be no reason for what is currently in the repo to not compile, there especially should be no reason for changing where `SimpleGrammar.hpp`'s include is should fix this issue either.

**Comment by Spartan322** [comment]
For now #33 fixes this issue, should later investigate why this is happening and a make a less hacky fix.
